// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvqdS2bOIivvleN8TwRxegrxh8HGMp0TY',
    appId: '1:602197336868:web:3f9c55fe8b24d1617989b1',
    messagingSenderId: '602197336868',
    projectId: 'reignforestcafe',
    authDomain: 'reignforestcafe.firebaseapp.com',
    storageBucket: 'reignforestcafe.appspot.com',
    measurementId: 'G-CPV1GJ11CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNKpJgEALgtZCPG2gH4k65EbJ42jaBAMk',
    appId: '1:602197336868:android:b88f3db40c25f7d77989b1',
    messagingSenderId: '602197336868',
    projectId: 'reignforestcafe',
    storageBucket: 'reignforestcafe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYoUmDLN2nOptm2NBlA2pOKLPeCighh68',
    appId: '1:602197336868:ios:1046dd7eadcec9317989b1',
    messagingSenderId: '602197336868',
    projectId: 'reignforestcafe',
    storageBucket: 'reignforestcafe.appspot.com',
    iosClientId: '602197336868-64543h4qgq0nqn35mh4mt9sk0dghhtuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhssReignForestCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYoUmDLN2nOptm2NBlA2pOKLPeCighh68',
    appId: '1:602197336868:ios:1046dd7eadcec9317989b1',
    messagingSenderId: '602197336868',
    projectId: 'reignforestcafe',
    storageBucket: 'reignforestcafe.appspot.com',
    iosClientId: '602197336868-64543h4qgq0nqn35mh4mt9sk0dghhtuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.nhssReignForestCafe',
  );
}
